import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { ThemeProvider } from 'styled-components';
import ChoosePokemon from './ChoosePokemon/ChoosePokemon';
import DadosGet from './DadosGet/DadosGet';
import HomePokemon from './HomePokemon/HomePokemon';
import { CardContextProvider } from '../contexts/Card/Card';
import Theme from '../../styles/Theme';

export default function Home() {
  return (
    <ThemeProvider theme={Theme}>
      <CardContextProvider>
        <Head>
          <title> Pokemon Grijp</title>
          <meta name="description" content="Generated by create next app" />
          <meta charSet="utf-8" />
        </Head>
        <HomePokemon />
      </CardContextProvider>
    </ThemeProvider>
  );
}
