import React from 'react';
import Head from 'next/head';
import Image from 'next/image';
import ChoosePokemon from './ChoosePokemon/ChoosePokemon';
import DadosGet from './DadosGet/DadosGet';
import HomePokemon from './HomePokemon/HomePokemon';

export default function Home() {
  return (
    <>
      <Head>
        <title> Pokemon Grijp</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
      </Head>
      <HomePokemon />
    </>
  );
}
