import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';
import DadosGet from './Home/DadosGet';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title> Pokemon Grijp</title>
				<meta name="description" content="Generated by create next app" />
				<meta charSet='utf-8'/>
			</Head>
			<DadosGet/>
		</div>
	);
}
